### ISSUE TITLE
way to close MethodsClient?

### ISSUE THREAD

**Issue by xchen10bu** [seratch/jslack-maintenance-releases#1]
Hi,
Is there a way to close/shutdown `MethodsClient slackClient = Slack.getInstance().methods(token);` ?
Because the underlying OkHttp is still running a non-daemon thread. Or is there a timeout set for it?
Thanks!

**Comment by seratch** [comment]
@xchen10bu Thanks for reporting this! As `OkHttpClient` is managed by `Slack` and its `SlackHttpClient` instance, not a `MethodsClient`. So, I've added `close` method to those two. I'll release a new version including the change soon.

**Comment by seratch** [comment]
version 3.4.0 has been released. Try it out.
