### ISSUE TITLE
Is there any plan for supporting Slack org-wide installation which is coming soon?

### ISSUE THREAD

**Issue by jemmy512** [seratch/jslack-maintenance-releases#16]
As title.

Thanks.

**Comment by seratch** [comment]
I'm sorry to say this but I'm not planning to add new features to this maintenance-mode library while I will apply fixes for critical bugs and security issues. If possible, please consider migrating to https://github.com/slackapi/java-slack-sdk - the migration should be easy.

**Comment by jemmy512** [comment]
Thank you @seratch.
